{% set name = "sos-python" %}
{% set version = "0.20.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 42360a24b6f88e9a0b6db30da33a885c2faaa1effc8c8135020adff623218663

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - sos-notebook >=0.19.4
    - sos >=0.19.8

test:
  requires:
    - nose
    - pytest
    - selenium
  imports:
    - sos_python

about:
  home: https://github.com/vatlab/sos-python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: SoS language module for Python2 and Python3
  doc_url: https://vatlab.github.io/sos-docs/
  dev_url: https://github.com/vatlab/sos-python

extra:
  recipe-maintainers:
    - BoPeng
