schema_version: 1

context:
  version: "0.20.3"

package:
  name: sos-python
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sos-python/sos_python-${{ version }}.tar.gz
  sha256: df46fd01ded90752d2e47c858d50a4fcf5dbdded71804e6c5b9ba1fc85d47d8c

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python =${{ python_min }}
    - setuptools
  run:
    - python >=${{ python_min }}
    - sos-notebook >=0.19.4
    - sos >=0.19.8

tests:
  - python:
      imports:
        - sos_python
      pip_check: true
  - requirements:
      run:
        - pip
        - python =${{ python_min }}
    script:
      - pip check

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: SoS language module for Python2 and Python3
  homepage: https://github.com/vatlab/sos-python
  repository: https://github.com/vatlab/sos-python
  documentation: https://vatlab.github.io/sos-docs/

extra:
  recipe-maintainers:
    - danielnachun
    - BoPeng
